- name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          gettext \
          pkg-config \
          libncurses5-dev \
          libblkid-dev \
          uuid-dev \
          zlib1g-dev \
          libselinux1-dev \
          libcap-dev \
          libmount-dev \
          libsmartcols-dev

    - name: Build and Test
      env:
        COMPILER: gcc
        COMPILER_VERSION: 10
        SANITIZE: yes
        CFLAGS: "-O2 -Wall -fPIC"
        LDFLAGS: "-L$(pwd)/lib -Wl,--whole-archive -lsmartcols -lblkid -luuid -lmount"
      run: |
        chmod +x .github/workflows/cibuild.sh
        sudo -E .github/workflows/cibuild.sh CONFIGURE MAKE