name: Build test
on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'
  push:
    branches:
      - 'cibuild'
      - 'master'
      - 'next'
      - 'stable/**'
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPILER: gcc
      COMPILER_VERSION: 10
      SANITIZE: no
      CFLAGS: "-m32 -O1"
      LDFLAGS: "-m32"
    steps:
      - uses: actions/checkout@v1
      - name: Ubuntu setup
        run: sudo -E .github/workflows/cibuild-setup-ubuntu.sh
      - name: Install 32-bit dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386 libncursesw5-dev:i386 libtinfo-dev:i386 libpam0g-dev:i386 libpam-modules:i386
      - name: Configure & Make
        run: |
          ./autogen.sh
          ./configure --host=i386-linux-gnu --build=i386-linux-gnu --enable-static --disable-shared --without-python --disable-makeinstall-chown --disable-use-tty-group --without-systemd --disable-login --disable-su --disable-sulogin --disable-nologin --disable-lslogins
          make V=1 LDFLAGS="-m32 -static -s" CFLAGS="-m32 -O1 -fno-stack-protector -fno-pie -fno-asynchronous-unwind-tables" cfdisk
      - name: Find binaries
        run: |
          find . -name "cfdisk" -type f -executable
      - name: Make install binaries
        run: |
          sudo mkdir -p /tmp/dest/usr/sbin/
          sudo find . -name "cfdisk" -type f -executable -exec cp -v {} /tmp/dest/usr/sbin/ \;
          sudo chmod 755 /tmp/dest/usr/sbin/cfdisk
          sudo strip -s /tmp/dest/usr/sbin/cfdisk
      - name: Make install
        run: sudo make install DESTDIR=/tmp/dest
      - name: Create artifact directory
        run: |
          mkdir -p artifacts
          cp -r /tmp/dest/* artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: util-linux-binaries
          path: artifacts/