name: Build test
on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'
  push:
    branches:
      - 'cibuild'
      - 'master'
      - 'next'
      - 'stable/**'
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPILER: gcc
      COMPILER_VERSION: 10
      SANITIZE: no
      CFLAGS: "-O0 -g3"
    steps:
      - uses: actions/checkout@v1
      - name: Ubuntu setup
        run: sudo -E .github/workflows/cibuild-setup-ubuntu.sh
      - name: Install ncurses
        run: sudo apt-get install -y libncursesw5-dev
      - name: Configure & Make
        run: |
          ./autogen.sh
          ./configure --enable-static --enable-all-programs --enable-static-programs --with-ncursesw --with-tinfo --without-python --disable-makeinstall-chown --disable-use-tty-group
          make V=1
      - name: Make install
        run: make install DESTDIR=/tmp/dest
      - name: Create artifact directory
        run: |
          mkdir -p artifacts
          cp -r /tmp/dest/* artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: util-linux-binaries
          path: artifacts/
  build-s390x:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu_latest
          run: |
            export COMPILER=gcc
            export COMPILER_VERSION=10
            export SANITIZE=no
            export QEMU_USER=1
            
            # name: Ubuntu setup
            .github/workflows/cibuild-setup-ubuntu.sh
            git config --global --add safe.directory "$PWD"
            # Configure & Make
            .github/workflows/cibuild.sh CONFIGURE MAKE
            # Check
            .github/workflows/cibuild.sh CHECK